on:
  workflow_call

jobs:
  replace_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const LABEL = 'Ship It';
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [LABEL],
            });
      - uses: actions/github-script@v6
        with:
          script: |
            const UNLABEL = 'Review/QA';
            try {
              github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: UNLABEL,
              });
            } catch (e) {
              if (e.status !== 404) throw e
            }
