on:
  workflow_call

jobs:
  replace_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const LABEL = 'In Progress';
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [LABEL],
            });
      - uses: actions/github-script@v6
        if: contains(github.event.pull_request.labels.*.name, 'Review/QA')
        with:
          script: |
            const UNLABEL = 'Review/QA';
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: UNLABEL,
            });
      - uses: actions/github-script@v6
        if: contains(github.event.pull_request.labels.*.name, 'Ship It')
        with:
          script: |
            const UNLABEL = 'Ship It';
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: UNLABEL,
            });
